name: Publish calendar
on: [workflow_dispatch]

env:
  WORKING_DIRECTORY: ./apps/calendar

jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
      - name: Check the package version
        id: cpv
        uses: PostHog/check-package-version@v2
        with:
          path: ${{ env.WORKING_DIRECTORY }}
      - name: Log when unchanged
        if: steps.cpv.outputs.is-new-version == 'false'
        run: 'echo "No version change"'
      - name: Cancel workflow
        if: steps.cpv.outputs.is-new-version == 'false'
        uses: andymckay/cancel-action@0.2

  publish-release:
    needs: check-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies

      - name: Build calendar
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm run build:calendar

      - name: Package dist as tarball
        working-directory: ${{ env.WORKING_DIRECTORY }}
        run: |
          npm pack
        # Esto genera un archivo tipo mi-lib-1.0.0.tgz en apps/calendar/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: calendar@${{ steps.cpv.outputs.committed-version }}
          name: "Calendar v${{ steps.cpv.outputs.committed-version }}"
          files: |
            ${{ env.WORKING_DIRECTORY }}/*.tgz
            ${{ env.WORKING_DIRECTORY }}/dist/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
